[package]
name = "opus"
version = "1.2.0"
edition = "2024_07"

[workspace]
members = ["scripts"]

# Build each contract as a standalone JSON file
[[target.starknet-contract]]
sierra = true
# strict libfuncs check - throw a compilation error
# when the code uses a libfunc that is not allowed
allowed-libfuncs-deny = true

[lib]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = ">= 2.13.0"
wadray = ">= 0.6.1"
access_control = ">= 0.5.0"

[dev-dependencies]
snforge_std = ">= 0.52.0"
assert_macros = ">= 2.13.0"

[scripts]
restart_devnet = "rm devnet_dump.json 2> /dev/null; starknet-devnet --seed 1087810753 --gas-price 1000 --initial-balance 1000000000000000000000000 --dump-on exit --dump-path devnet_dump.json"
load_devnet = "starknet-devnet --seed 1087810753 --gas-price 1000 --initial-balance 1000000000000000000000000 --dump-path devnet_dump.json"
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120
breaking-behavior = { tuple = "LineByLine", fixed_array = "LineByLine", macro_call = "LineByLine" }

[tool.cairo-lint]
unwrap_syscall = false

[profile.coverage]
inherits = "dev"

[profile.coverage.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "default"
