name: Lint and Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1

      - name: Format check
        run: scarb fmt --workspace --check

      - name: Build
        run: scarb build

      - uses: foundry-rs/setup-snfoundry@v3

      - name: Run dev tests
        run: scarb --profile dev test

  coverage:
    needs: lint-and-test
    uses: ./.github/workflows/coverage.yml
    secrets: inherit
