name: Cairo tests and coverage

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --workspace --check
      - run: scarb build

      - uses: foundry-rs/setup-snfoundry@v3

      - name: Install cairo-coverage
        run: curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Build tests
        run: scarb build --test

      # Split tests to avoid timeout/resource overload on Github Actions
      - name: Run Purger setup tests
        run: scarb test purger --skip absorb --skip liquidate --save-trace-data

      - name: Run Purger tests for full absorption
        run: scarb test purger --skip setup --skip penalty --skip liquidate --skip partial --save-trace-data

      - name: Run Purger tests for partial absorption
        run: scarb test partial_absorb --save-trace-data

      - name: Run Purger tests for liquidation
        run: scarb test purger --skip setup --skip penalty --skip absorb --save-trace-data

      - name: Run Shrine tests
        run: scarb test shrine --save-trace-data

      - name: Generate coverage report
        run: cairo-coverage run $(find snfoundry_trace -name "*.json" -type f)

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.0.0

      - name: Generate coverage report
        run: cairo-coverage run $(find snfoundry_trace -name "*.json" -type f)

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.0.0

