name: Cairo tests and coverage

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --workspace --check
      - run: scarb build

      - uses: foundry-rs/setup-snfoundry@v3

      - name: Install cairo-coverage
        run: curl -L https://raw.githubusercontent.com/software-mansion/cairo-coverage/main/scripts/install.sh | sh

      - name: Run tests
        run: scarb test allocator --save-trace-data

      - name: Generate coverage report
        run: cairo-coverage run $(find snfoundry_trace -name "*.json" -type f)

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.0.0

